services:
  jenkins:
    #image: jenkins/jenkins # :latest (weekly), :lts
    build:
      context: .
    ports:
      - "8090:8080"
      - "127.0.0.1:2222:2222"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # for DooD
    restart: unless-stopped
  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    ports:
      - "8091:8025" # web UI
    restart: unless-stopped

volumes:
  jenkins_home:

# FYI https://www.jenkins.io/doc/book/installing/docker/
# jenkins/jenkins image repo: https://github.com/jenkinsci/docker
