services:
  email:
    image: mailhog/mailhog
    platform: linux/amd64 # for Apple Silicon macs
    ports:
      - "127.0.0.1:1025:1025" # SMTP
      - "127.0.0.1:8025:8025" # web UI
    restart: unless-stopped
